import './globals.css'
import { Bitter } from 'next/font/google'

const bitter = Bitter({ subsets: ['latin'], variable: "--font-bitter" })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={bitter.variable}>{children}</body>
    </html>
  )
}
