import Head from "next/head";
import DarkModeIcon from "../components/DarkModeIcon";
import style from "../styles/Home.module.css";
import { Rowdies, Roboto_Slab } from "@next/font/google";
import Image from "next/image";

export const notoSerif = Roboto_Slab({
  subsets: ["latin"],
  weight: "400",
});

export const rowdies = Rowdies({
  subsets: ["latin"],
  weight: "400",
});

export default function Home() {
  return (
    <div className="dark">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="2xl:mx-96 xl:mx-60 xl:mx-24 md:mx-10 mx-4 my-4">
        <nav className="flex items-center justify-center">
          <h1 className={rowdies.className}>Thinh Nguyen</h1>
        </nav>
        <header className="my-20 flex items-center xl:flex-row flex-col-reverse">
          <div className="xl:text-left text-center xl:mx-0 lg:mx-56 md:mx-24 sm:mx-16 mx-4">
            <h2 className={notoSerif.className + " text-2xl font-bold my-4"}>
              Hello there! My name is{" "}
              <span className="font-bold color-blue-dark">Thinh Nguyen</span>
            </h2>
            <h3 className={notoSerif.className}>
              I&apos;m a{" "}
              <span className="font-bold color-blue-dark">web developer</span>.
              Currently I&apos;m learning about{" "}
              <span className="font-bold color-blue-dark">web development</span>{" "}
              and also{" "}
              <span className="font-bold color-blue-dark">
                server management
              </span>
              . My dream is to build a start-up, that will make me a billionaire
              or the richest man in the world.
            </h3>
            <div className="w-full flex sm: items-center xl:justify-around justify-center sm:flex-row flex-col my-2">
              <a
                href="https://github.com/CutieCat6778"
                className="no-underline color-black"
              >
                <button className={notoSerif.className + " my-2 sm:my-10 xl:mr-0 mr-8 " + style.btn}>
                  Not my github
                </button>
              </a>
              <a
                href="https://instagram.com/txzje"
                className="no-underline color-black"
              >
                <button className={notoSerif.className + " my-2 sm:my-10 " + style.btn}>
                  My instagram
                </button>
              </a>
            </div>
          </div>
          <Image
            src="/ilu-0.svg"
            height={456}
            width={608}
            alt="Ilustration about me"
            priority
          />
        </header>
        <section className="my-20 flex items-center xl:flex-row flex-col">
          <Image
            src="/ilu-1.svg"
            height={456}
            width={608}
            alt="Ilustration about me"
          />
          <div className="xl:mx-0 lg:mx-72 md:mx-24 sm:mx-16 mx-4 xl:text-left text-center">
            <h2 className={notoSerif.className + " text-2xl font-bold my-4"}>
              Wanna <span className="font-bold color-pink">contact</span> me?
            </h2>
            <h3 className={notoSerif.className}>
              I&apos;m currently a{" "}
              <span className="font-bold color-pink">student</span>, so kinda
              busy. I will try my best to answer all email and message{" "}
              <span className="font-bold color-pink">within 2-3 days</span>. I
              have a very random life so yeah, it is hilarious 🤣
            </h3>
            <div className="w-full flex items-center justify-center">
              <a
                href="mailto:thinh@thinh.tech"
                className="no-underline color-black"
              >
                <button
                  className={notoSerif.className + " my-10 " + style.btn_pink}
                >
                  Contact meee
                </button>
              </a>
            </div>
          </div>
        </section>
        <footer className={notoSerif.className + " w-full text-center"}>
          2023 © Thinh Nguyen all rights reserved
        </footer>
      </main>
    </div>
  );
}
