name: Branch v6

on:
  push:
    branches:
      - v6

jobs:
  version:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - run: git config --global user.name 'CutieCat6778'
      - run: git config --global user.email 'thinhnguyenhuuhung@gmail.com'
      - run: npm version patch -m "[RELEASE] %s"
      - run: git push
  cypress-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress.io
        uses: cypress-io/github-action@v5.0.8
        with:
          build: npm run build
          start: npm start