name: Portfolio

on:
  push:
    branches:
      - v5

jobs:
  version:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - run: git config --global user.name 'CutieCat6778'
      - run: git config --global user.email 'thinhnguyenhuuhung@gmail.com'
      - run: npm version patch -m "[RELEASE] %s"
      - run: git push